site_name: AllFunds Wiki
site_url: https://mdharisbinfaiz.github.io/wikipages/
repo_url: https://github.com/mdharisbinfaiz/wikipages.git
edit_uri: https://github.com/mdharisbinfaiz/wikipages-/edit/main/docs/

#theme: readthedocs
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: "#"
plugins:
 - kroki:
    ServerURL: https://kroki.io
    FencePrefix: kroki-
    EnableBlockDiag: True
    Enablebpmn: True
    EnableMermaid: False
    EnableDiagramsnet: True
    FileTypes:
      - png
      - svg
 - plantuml:
    puml_url: https://www.plantuml.com/plantuml/
    num_workers: 8
 - mermaid2:
 - print-site:
     

